plugins { id 'com.android.application' }

android {
    namespace 'com.aurelius.businesstycoon'
    compileSdk 35

    defaultConfig {
        applicationId 'com.aurelius.businesstycoon'
        minSdk 24
        targetSdk 34
        versionCode 5
        versionName '5.0.0'
    }

    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }
}

dependencies {
    implementation 'androidx.work:work-runtime:2.9.1'
}
