plugins {
    id 'com.android.application'
}

android {
    namespace 'com.atrangiriders.ledger'
    compileSdk 35

    defaultConfig {
        applicationId 'com.atrangiriders.ledger'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
            versionNameSuffix ''
            debuggable false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.6.2'
}
